apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ nginx_deployment_name }}"
  labels:
    app: nginx
    version: v0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: "{{ nginx_deployment_image }}"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ nginx_deployment_name }}"
data:
  DEPLOYMENT_SECRET: "{{ deployment_secret }}"

